# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 03:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='project.Category'),
            preserve_default=False,
        ),
    ]
