# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('project', '0003_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(to='user.CustomUser'),
        ),
    ]
