# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 22:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20171103_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='publish_date',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='published date'),
        ),
    ]
