# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_category_projects_wanted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='projects_wanted',
        ),
    ]
