# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20171104_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='publish_date',
            field=models.DateField(default='11/04/17', verbose_name='published date'),
        ),
    ]
