# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 01:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20)),
                ('pitch', models.TextField(max_length=250)),
                ('description', models.TextField()),
                ('publish_date', models.DateTimeField(verbose_name='published date')),
                ('accept_applicants', models.BooleanField()),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
