# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_auto_20171028_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='project_list',
        ),
        migrations.AddField(
            model_name='project',
            name='project_categories',
            field=models.ManyToManyField(to='share.Categories'),
        ),
    ]
